#! /usr/bin/env python
# encoding: utf-8

bld.program(
    features='cxx',
    source=['kodo.cpp'],
    target='kodo',
    linkflags=['--bind', '-O3'],
    use=['kodo_rlnc_includes'],
    export_includes=['..'])


